site_name: Slurm & Bash Workflows
site_description: 'How to build simple workflows using Bash and Slurm'
site_author: 'cal'
docs_dir: docs/

repo_name: CallumWalley/slurm-bash-workflows
repo_url: https://https://github.com/CallumWalley/slurm-bash-workflows
#edit_uri: tree/master/docs # Uncomment to define a different URI/URL for the "edit" option

nav:
  - Welcome: index.md
theme:
  name: 'material'
  #favicon: 'assets/images/favicon.png'
  palette:
    scheme: 'slate'
    primary: 'indigo'
    accent: deep purple
  features:
  # Navigation:
  #
  #- navigation.expand      # Expand all collapsable sections.
  #- navigation.instant     # Instant loading pages.
  #- navigation.indexes     # Attach pages directly to Sections. Incompatible with "toc.integrate"
  #- navigation.sections    # Render top sections as groups.
  - navigation.tabs         # Render top sections as tabs at the top.
  #- navigation.tabs.sticky # Tabs won't disappear when scrolling down. Requires "navigation.tabs".
  - navigation.top         # Adds a "Back to top" that is shown when scrolling up.
  #- navigation.tracking    # Updates the url with highlighted section anchor.
  
  # Search
  #
  #- search.highlight # Search will highlight the searched word(s) on the page.*
  #- search.share     # Adds an option to share a search query link.*
  #- search.suggest   # Search will suggest the likeliest completion for a word.*
  
  # Table of Contents
  #
  - toc.integrate          # Include the TOC sections in the left navugation.
  
  #logo: 'material/library'
#extra_css:
#extra_javascript:
extra:
#   social:
#     - icon: 'fontawesome/brands/github'
#       link: 'https://github.com/Andre601/mkdocs-template'
  generator: true
markdown_extensions:
  - markdown.extensions.admonition:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  #- pymdownx.arithmex:
  #- pymdownx.b64:
  #- pymdownx.betterem:
  #- pymdownx.caret:
  #- pymdownx.critic:
  #- pymdownx.details:
  #- pymdownx.emoji:
  #- pymdownx.escapeall:
  #- pymdownx.extra:
  #- pymdownx.extrarawhtml:
  #- pymdownx.highlight:
  #- pymdownx.inlinehilite:
  #- pymdownx.keys:
  #- pymdownx.magiclink:
  #- pymdownx.mark:
  #- pymdownx.pathconverter:
  #- pymdownx.progressbar:
  #- pymdownx.smartsymbols:
  #- pymdownx.snippets:
  #- pymdownx.striphtml:
  #- pymdownx.superfences:
  #- pymdownx.tabbed:
  #- pymdownx.tasklist:
  #- pymdownx.tilde:
